stages:
  - build
  - test
  - deploy

# WARN: global before script gets overwritten by per job before_script
before_script:
  - export IMAGE_TAG=${CI_COMMIT_TAG:-$CI_COMMIT_REF_SLUG}

build-images:
  image: $PREVISION_REGISTRY_ADDR/prevision/docker:19.03.1
  stage: build
  script:
    - cd ci
    - export TAG=$IMAGE_TAG
    - sh Makefile
    - docker push $PREVISION_REGISTRY_ADDR/prevision/prevision-python-tests:$CI_COMMIT_REF_SLUG

lint-python-sdk:
  image: $PREVISION_REGISTRY_ADDR/prevision/prevision-python-tests:$CI_COMMIT_REF_SLUG
  stage: test
  script:
    - make lint

coverage-python-sdk:
  image: $PREVISION_REGISTRY_ADDR/prevision/prevision-python-tests:$CI_COMMIT_REF_SLUG
  stage: test
  script:
    - cat $connectors_config > utests/connectors_config.py
    - make utests-ci
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  only:
    - tags
    - web
    - schedules
  artifacts:
    paths:
      - utests/coverage_html_report/
      - utests/test_results.xml
    reports:
      junit: utests/test_results.xml

pages:
  stage: deploy
  dependencies:
    - coverage-python-sdk
  script:
    - mv utests/coverage_html_report/ public/
  only:
    - tags
    - web
    - schedules
  artifacts:
    paths:
        - public
    expire_in: 30 days
    
